
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gate"
spec:
  stages:
    - name: "test"
      sequences:
        - name: "quality"
          tasks:
            - name: "evaluation"
              properties:
                timeframe: "2m"
