apiVersion: v2
actions:
  - name: "Run k6"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run k6 with Keptn"
        maxPollDuration: 1200
        files:
          - files/k6
        image: "loadimpact/k6"
        cmd: ["k6"]
        args: ["run", "/keptn/files/k6/test.js"]